/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#003d9b",
        "primary-container": "#0052cc",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#c4d2ff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2",
        "inverse-primary": "#b2c5ff",
        secondary: "#904d00",
        "secondary-container": "#fd8b00",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#603100",
        "on-secondary-fixed": "#2f1500",
        "on-secondary-fixed-variant": "#6e3900",
        tertiary: "#004b59",
        "tertiary-container": "#006477",
        "tertiary-fixed": "#afecff",
        "tertiary-fixed-dim": "#48d7f9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#76e2ff",
        "on-tertiary-fixed": "#001f27",
        "on-tertiary-fixed-variant": "#004e5d",
        surface: "#faf9ff",
        "surface-dim": "#ccdaff",
        "surface-bright": "#faf9ff",
        "surface-container": "#e9edff",
        "surface-container-low": "#f1f3ff",
        "surface-container-high": "#e1e8ff",
        "surface-container-highest": "#d8e2ff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d8e2ff",
        "surface-tint": "#0c56d0",
        "on-surface": "#051a3e",
        "on-surface-variant": "#434654",
        "inverse-surface": "#1d3054",
        "inverse-on-surface": "#edf0ff",
        background: "#faf9ff",
        "on-background": "#051a3e",
        outline: "#737685",
        "outline-variant": "#c3c6d6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["DM Sans", "Inter", "sans-serif"],
        display: ["Sora", "Inter", "sans-serif"],
      },
      spacing: {
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(0, 82, 204, 0.08)",
        "ambient-lg": "0 30px 60px rgba(0, 82, 204, 0.12)",
      },
      backgroundImage: {
        "adventure-gradient": "linear-gradient(135deg, #0052cc 0%, #003d9b 100%)",
      },
    },
  },
  plugins: [],
};
